### ISSUE TITLE
Readme is Unclear about functionality.

### ISSUE THREAD

**Issue by majestrate** [ossfriday/ossfriday#114]
I can't seem to find any documentation on what this software does and what the long term goals are.

Adding such to the readme would most definately increase engagement.

**Comment by Charlotteis** [comment]
Hi!

This repository does not hold software, but rather holds the code that builds the ossfriday.com website. 

The website explains what it is about, namely a site that will list all the open source pull requests you have done on Fridays. It has guides to open source contributing, and all of this works toward encouraging folk to contribute to Open Source.

I hope this helps.

Our README certainly looks a bit outdated on "What is this" and I will try and make it clearer later tonight.

But, the website is documentation and the long term goal, so I'm not quite sure what you are looking for? :)

Best,
James

**Comment by MikeMcQuaid** [comment]
This was clarified by @Charlotteis's great work in https://github.com/ossfriday/ossfriday/issues/115.
