### ISSUE TITLE
Add script/bootstrap

### ISSUE THREAD

**Issue by bkeepers** [ossfriday/ossfriday#12]
I had to type, like, at least 3 commands to get this app running. :trollface: 

This is just a reminder to add a [`script/bootstrap`](https://github.com/github/scripts-to-rule-them-all) to make it easier.

*Edit*: Most of [this](https://github.com/ossfriday/ossfriday#getting-started) can be scripted.

**Comment by maxcell** [comment]
I was thinking about taking a hold of this! I had a few questions though based upon your referenced article + the setup documentation. With our script, I was thinking we would have,
1. [ ] Install rbenv (or RVM 😛)
2. [ ] Installing ruby-lang by the `.ruby-version`
3. [ ] Installing Node/NPM
4. [ ] Installing PostgreSQL

I might be overthinking it, but my main concern comes from how system-agnostic we want to maintain this file. In the [`script/bootstrap`](https://github.com/github/scripts-to-rule-them-all/blob/master/script/bootstrap#L10) file above, it mentions looking for Homebrew dependencies and in our [documentation we also mention installation by Homebrew](https://github.com/ossfriday/ossfriday#getting-started) so should be keep it to that or should we just look towards maintaining it through bash?

**Comment by MikeMcQuaid** [comment]
@maxcell Awesome! I'd suggest looking at https://github.com/github/scripts-to-rule-them-all/blob/master/script/bootstrap which is a good starting point. I'd assume the use of certain tools (`rbenv`, Homebrew, `Brewfile`, macOS) for now and people can always extend it as to their liking. https://github.com/github/homebrew-bootstrap/ may also be useful for providing scripts that are more involved, handle a bunch of edge-cases and can be run just by adding e.g. `brew bootstrap-nodenv-node` to `script/bootstrap` and `tap "github/bootstrap"` to the `Brewfile`. Feel free to open a PR early even if not complete and we can talk more there. Good luck and thanks ❤️!
