### ISSUE TITLE
BASEDEF open source contribution methodology

### ISSUE THREAD

**Issue by begriffs** [ossfriday/ossfriday#128]
Hi there, glad to see your open source Friday guide. It's a topic near to my heart. Wrote about a technique for organizing technical and non-technical contributors that I thought you'd like. Perhaps you can incorporate the BASEDEF idea into your guide.

https://begriffs.com/posts/2016-01-29-making-twenty-percent-time-work.html

Cheers.

**Comment by MikeMcQuaid** [comment]
Thanks for the kind words and blog post. We're not interested in incorporating these changes at this time but thanks again for the suggestion.
