### ISSUE TITLE
RFE: Add to Calendar with user's timezone

### ISSUE THREAD

**Issue by miurahr** [ossfriday/ossfriday#131]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## Problem

Add to calendar page use UK/London timezone fixed.
It is better to adjust timezone according to a address user lived.

## Steps to Reproduce

1. go to user page
2. scroll page to "Set a reminder" section
3. click "Add to Calender"

## Related component 

Addtocalendar NPM package. https://addtocalendar.com/

**Comment by MikeMcQuaid** [comment]
We already do this but there are bugs with the feature: https://github.com/ossfriday/ossfriday/issues/105
