### ISSUE TITLE
Why not starting a translation project on translation community platform?

### ISSUE THREAD

**Issue by miurahr** [ossfriday/ossfriday#149]
Now we can start translation meta project on Transifex or similar platform such as translatewiki.net.

You can see instructions at https://docs.transifex.com/integrations/rails/ for transifex.

There are many volunteers who may help us to localize ossfriday site.

**Comment by MikeMcQuaid** [comment]
@miurahr Great idea! Are either of these freely available for open source projects? Do you have experience using either of them?

**Comment by miurahr** [comment]
@MikeMcQuaid These are freely available for OSS and very famouse. Many OSS leaders knows it and use it.

**Comment by MikeMcQuaid** [comment]
@miurahr Great, thanks!

**Comment by miurahr** [comment]
https://github.com/pejuko/i18n-translators-tools
This might be helpful for workflow; (1) convert yml to PO file (2) upload PO files (3) download updated translation from transifex in PO file. (4) merge back to yml

Does anyone who have experience to use the tool?

**Comment by miurahr** [comment]
Transifex provide utility tool for this purpose.
https://docs.transifex.com/client/introduction

**Comment by MikeMcQuaid** [comment]
@miurahr Thanks! I've signed up for an account and invited you: https://www.transifex.com/open-source-friday/open-source-friday/dashboard/

Can you let me know if it looks OK to you? There's a few strings it noticed are missing from the Japanese translation; maybe you could try and translate them and then I can try the process of getting a translation back here? Thanks!

**Comment by MikeMcQuaid** [comment]
@miurahr This has now moved to https://www.transifex.com/github-open-source/open-source-friday/dashboard/

**Comment by miurahr** [comment]
Looks good on transifex. Could you also give me a reviewer permission?
I'd like to update some terms and ask you to import it to the projects soon.

**Comment by knowtheropes35** [comment]
Eh?

**Comment by MikeMcQuaid** [comment]
@knowtheropes35 If you don't have anything to add to this thread please don't comment, thanks.

@miurahr Will do, thanks!

**Comment by MikeMcQuaid** [comment]
@miurahr Done!

**Comment by miurahr** [comment]
@MikeMcQuaid You can find a translated result on Transifex now. The data is fully translated and some are tagged as reviewed. We will export it and import here. I'd like to propose  closing here when you have all work flows done successfully.
