### ISSUE TITLE
Show all organizations on profile page

### ISSUE THREAD

**Issue by kevinbarabash** [ossfriday/ossfriday#188]
Currently it only shows the first organization a person's joined which may not be representative of the organizations that they contribute to the most.

**Comment by MikeMcQuaid** [comment]
We show all public organisations:

<img width="981" alt="screen shot 2018-01-27 at 09 32 48" src="https://user-images.githubusercontent.com/125011/35470639-0fdd8268-0345-11e8-8a83-8825f4a5c401.png">

**Comment by kevinbarabash** [comment]
On my github profile it shows four organizations:
<img width="244" alt="screen shot 2018-01-27 at 10 55 45 am" src="https://user-images.githubusercontent.com/1044413/35473606-e3b80206-0350-11e8-9561-eccb7c57c3fc.png">

But on my opensourcefriday profile it only shows one:
<img width="750" alt="screen shot 2018-01-27 at 10 55 51 am" src="https://user-images.githubusercontent.com/1044413/35473609-f91d8094-0350-11e8-8270-02bb6c51d76b.png">

**Comment by MikeMcQuaid** [comment]
All _public organisations_; your GitHub profile page only shows one to me which matches your Open Source Friday profile.

**Comment by kevinbarabash** [comment]
I've updated my public/private setting for those other repos, but they're still not showing up.  Does it take a while for the changes to propagate?

**Comment by MikeMcQuaid** [comment]
Yep.
