### ISSUE TITLE
Skylight Instrumentation

### ISSUE THREAD

**Issue by chancancode** [ossfriday/ossfriday#194]
Hello!

I work at [Skylight](https://www.skylight.io/). We are launching a [program](https://www.skylight.io/oss) to offer free Skylight accounts to open source apps (similar to Github and Travis), so I am reaching out to see if this is something you would be interested in.

If you’re not already familiar with Skylight, it is a smart profiler for Rails apps. Skylight makes it easy to pinpoint performance issues in Rails applications.

We work on a lot of open source projects ourselves, and in our experience it can be pretty hard to get contributors to work on application performance issues. Few contributors consider working on performance problems, and the ones that might be interested may not even know where to start. By making performance information more accessible, we hope to inspire potential contributors to tackle slow parts of your app, and have a good way to see if their contributions helped.

Integrating Skylight to a Rails application is very easy. All you have to do is add the gem to your Gemfile and set an environment variable with your authentication token. (We are happy to send a pull request.) If you’re interested in setting this up or if you have any questions, you can reach us here or at support@skylight.io.

We'd also love to feature you on our website as one of the first open source organizations using Skylight. We hope you’ll join us in helping to make performance an accessible way to contribute to an open source project!

**Comment by chancancode** [comment]
For reference, this is the [Skylight dashboard](https://oss.skylight.io/app/applications/g0gJSNnzYAws/) for [The Odin Project](https://www.theodinproject.com/).

**Comment by knowtheropes35** [comment]
Excuse me as my email was hacked and was mass posting exactly what? And where? I am I little bit oce policing the masses that have to do stupid things
