### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by andrew** [ossfriday/ossfriday#2]
Kicking off a discussion around OSS Friday, a movement, inspired by https://24pullrequests.com, to encourage people to contribute to open source every Friday.

*Alternative name: 52 pull requests* 🤣 

Some of the things that worked well for 24 Pull Request that I'd like replicate:

- **opt-in for maintainers** - only suggesting projects that maintainers have suggested means we don't send a swarm of extra maintainer work to someone who doesn't want it or can't handle it.
- **Wisdom of crowds** - if lots of people are doing the same thing at the same time more people will make an effort to join in
- **Gamification** - a little bit of gamification goes a long way, I'm thinking streaks for having done some kind of contribution every Friday throughout the year
- **Automation** - many efforts around cultivating open source contributions that require humans tend to fizzle out as the humans involved can't sustain the level of work required to keep it going, 24 Pull Requests pretty much runs itself now which is why it's been so easy to keep it going for 5 years
- **Emails** - sending out regular reminder emails with suggested contribution content works great to give people a kick to keep them going, optional for people who hate email.

Things I'd like to try:

- **Focusing on issues rather than projects** - trying to find a project to contribute to and then find something to do on that project is tricky, instead let's get maintainers to label issues that they want to promote to new contributors with `ossfriday` along with related labels like `Your First PR`, `first-timers-only` and `help wanted`

- **not tied to pull requests** - there are lots of ways someone can contribute to an open source project that doesn't require opening a PR on GitHub, we should encourage things like documentation, issue triage, stackoverflow answering, support forum helping, event organising, blogging as well as code contributions

I'm planning on getting something basic together (in ruby of course) before 6th January, the first Friday of 2017 and we can iterate from there 🚀 

Would love to hear your ideas, thoughts, feedback, contributions, gifs and emoji reactions, Happy Friday 🍻

**Comment by MikeMcQuaid** [comment]
Sounds really great. Something I thought of (that could be addressed later if necessary, by me) is trying to model this so that companies can figure out what is valuable to them and encourage their engineers to take part.

**Comment by davydovanton** [comment]
awesome idea 👍 
What do you think about integration with [my project](https://gist.github.com/davydovanton/46d198e92012233aff591abf7673795e) too? :)

**Comment by nschonni** [comment]
Maybe center it around a Gitter/Slack channels so people can just drop in and spin off to discuss if they find a project/maintainer they want to work with

**Comment by m1guelpf** [comment]
@andrew Awesome idea!

**Comment by andrew** [comment]
Couple other thoughts:

- *Avoid rewards* - Getting free t-shirts or other kinds of gifts tends to bring out bad behaviour like prs that change a single line of whitespace, which waste maintainers time and energy, the rewards should be a bit less tangible

- *There are three target audiences* - Individual contributors, maintainers and companies (h/t @MikeMcQuaid) are the three types of audience we should be catering to, with documentation for each one on how to get involved. I can see the homepage being split in half for contributors and maintainers and then companies slightly further down.

@nschonni we'll definitely get a slack room set up but I think everything should be geared towards async comms so as not to put any blockers to contributions, especially considering timezone differences between maintainers and contributors

@davydovanton we should definitely link to your project, I can see us having a list of related projects like on @24pullrequests: https://24pullrequests.com/contributing

**Comment by bbrks** [comment]
Such a great idea! I'm fully behind this! I've always been a fan of 24PRs, but it always seems a bit too time-intensive. Making an effort once a week to contribute to the OSS community sounds ideal for me.

**Comment by Charlotteis** [comment]
> not tied to pull requests - there are lots of ways someone can contribute to an open source project that doesn't require opening a PR on GitHub, we should encourage things like documentation, issue triage, stackoverflow answering, support forum helping, event organising, blogging as well as code contributions

I am super interested this and want it to happen!

Also one thought:

Call it OSSFriday, but maybe count any contribution during the week? For instance, i might have an all day meeting from hell and can't make my contribution, but did a great one on the Saturday morning.

Really excited about this.

Thought for later:

Maybe we could have some sort of admin system where we could surface some Issues we think would be really good? If it is open, it could be a little flash banner at the top of the page. My only concern is one issue getting a billion people saying "can I do this" on the issue, which we got a lot of at Hoodie during Hacktoberfest because folk didn't seem to wanna read that the issue had already been claimed.

**Comment by andrew** [comment]
> > not tied to pull requests - there are lots of ways someone can contribute to an open source project that doesn't require opening a PR on GitHub, we should encourage things like documentation, issue triage, stackoverflow answering, support forum helping, event organising, blogging as well as code contributions
> I am super interested this and want it to happen!

I've been thinking of it as more of an open source contribution diary of how you contributed, "This friday I helped triage some bugs on https://github.com/rust-lang/crates.io/", which could be automatically filled out for activity on github like opening, commenting, closing or merging issues/prs on GitHub but also free text for less easily trackable things.

> Call it OSSFriday, but maybe count any contribution during the week? For instance, i might have an all day meeting from hell and can't make my contribution, but did a great one on the Saturday morning.

Isn't that just the standard GitHub contribution graph? If you can do anything on any day it looks it's specialness a bit, it's just general contributions to open source and doesn't really need the project to exist, but if we have a diary-style entry you can always say what you did earlier in the week?

Highlighting some great issues would be good, and we can randomize who we show them too and perhaps stop showing issues that have been commented on recently.

**Comment by kentcdodds** [comment]
> there are lots of ways someone can contribute to an open source project that doesn't require opening a PR on GitHub
> etc...

Just pushing this out there. Not certain how it could play a roll, but maybe it could be used to give ideas of types of contribution for contributors and perhaps maintainers could implement it if they so desire: [all-contributors](https://github.com/kentcdodds/all-contributors)

**Comment by Charlotteis** [comment]
> I've been thinking of it as more of an open source contribution diary of how you contributed, "This friday I helped triage some bugs on https://github.com/rust-lang/crates.io/", which could be automatically filled out for activity on github like opening, commenting, closing or merging issues/prs on GitHub but also free text for less easily trackable things.

Sounds awesome.

> Isn't that just the standard GitHub contribution graph? If you can do anything on any day it looks it's specialness a bit, it's just general contributions to open source and doesn't really need the project to exist, but if we have a diary-style entry you can always say what you did earlier in the week?

Makes sense :)

**Comment by andrew** [comment]
@kentcdodds we can definitely use that list to help with the maintainers documentation

**Comment by LappleApple** [comment]
@andrew Thanks for doing this (and all your other work). Will try to get some colleagues to participate.

**Comment by LappleApple** [comment]
@MikeMcQuaid @andrew Would be interested in talking to you about this. Will you be at FOSDEM?

**Comment by MikeMcQuaid** [comment]
@LappleApple I am, yes! Let's talk. Making GitHub (my employer) better for Open Source is my job now too.

**Comment by andrew** [comment]
@LappleApple yeah I'm planning on going (mostly because there are lots of other great people going to be in town at the same time!), would be great to chat about this, cc @benjam

**Comment by LappleApple** [comment]
@MikeMcQuaid Super. BTW, we-Zalando/I'm in touch with several of your colleagues, including @bkeepers + @nayfia (who've been chiming in on [this other thread](https://github.com/hoodiehq/camp/issues/102#issuecomment-270045817), btw). For the work I do, the two threads have lots of overlap.

**Comment by LappleApple** [comment]
@andrew Great to hear. I will email you and Mike now offline...

**Comment by MikeMcQuaid** [comment]
@LappleApple We're teammates now so there may be some overlap in conversations here 😁

**Comment by crichID** [comment]
@andrew This is such a :sparkles: idea! The GitHub Training Team has recently open sourced our training materials and we are working on a new course in the month of January on "How to Contribute to Open Source". We :hand: to be testers for anything you want to try out!

/cc @hollenberry @hectorsector @brianamarie @beardofedu

**Comment by LappleApple** [comment]
Hi @crichID: can you share the link? Would love to take a look.

**Comment by crichID** [comment]
> Hi @crichID: can you share the link? Would love to take a look.

@LappleApple absolutely! The courses are available here: https://services.github.com/on-demand/ and the repo is here: https://github.com/github/training-kit.

**Comment by nayafia** [comment]
Love the focus on issues and non-PR contributions. Not only does it lower the barrier to contribution, but I think this whole project will help define those norms for similar events/initiatives.

Excited to see this happen, happy to promote and support however I can!

Sad to miss you all at FOSDEM this year but look forward to hearing about it from @mikemcquaid and @bkeepers :)

**Comment by LappleApple** [comment]
That's great, @crichID. We touch upon contributing to OS in our [how-to](https://github.com/zalando/zalando-howto-open-source#how-to-become-a-contributor), which is primarily geared toward our own eng team but has made the rounds on the Internet a little. It links to some resources on contributing (we don't need to reinvent the wheel), and I'd like to add your Jan class as a link when it's available.

I wonder if you will also be at FOSDEM. Looking forward to catching up with Mike and Andrew about company-level "how to contribute" questions. This is what I am currently working on.

**Comment by angiemaguire** [comment]
@andrew This is a fantastic idea! Let me know if Ladies of Code can help :)

**Comment by angiemaguire** [comment]
@LappleApple I'm not but keep me in the loop and let me know if we can be of any help :)

**Comment by MikeMcQuaid** [comment]
@LappleApple @angiemaguire Cool so many people are into this! A gentle suggestion: in the interests of being async/distributed friendly: let's either have some async conversation on GitHub itself (my preferred option) or a e.g. Google Hangout some time before/after FOSDEM where other folks who aren't FOSDEMing can 🔉 in.

**Comment by BenJam** [comment]
+1 for responsible communication methods.

**Comment by LappleApple** [comment]
@MikeMcQuaid Yes, of course. I was only trying to find out who will be there already.

**Comment by MikeMcQuaid** [comment]
@LappleApple 👍 ❤️: totally not a criticism, just a suggestion. Looking forward to meeting there 😁

**Comment by acabunoc** [comment]
Really loving this! Nice work @andrew 👏 

With the focus on issues rather than pull requests, this could be a good space to show what makes a good issue. I can see this encouraging maintainers to write and mentor more issues for first timers.

Happy to help where I can (since showing maintainers how to do the above is mostly what I think of nowadays)

**Comment by andrew** [comment]
I've taken way too much on this week and something had to give so ossfriday will have to wait for a couple more weeks before launching

**Comment by Thetoxicarcade** [comment]
You go Andrew. We still love your work.

**Comment by bbrks** [comment]
@andrew Let us know if there's anything specific anybody can do to help.

**Comment by duergner** [comment]
One point that came up today during a meeting where we've been talking about OSSFriday was related to how to "ensure" not all people just want to contribute to those ten most well known projects. Does anyone else share these concerns?

**Comment by MikeMcQuaid** [comment]
@duergner Sorry, maybe being stupid but: where did the ten most well known projects come from?

**Comment by duergner** [comment]
@MikeMcQuaid it's been based on some experience from Hacktoberfest one of the developers told when he looked to contribute to projects but somehow everyone wanted to contribute to the same projects mainly.

**Comment by MikeMcQuaid** [comment]
Closing this (awesome) discussion but would welcome more thoughts in https://github.com/ossfriday/ossfriday/issues/21.
