### ISSUE TITLE
Email campaign ideas

### ISSUE THREAD

**Issue by nayafia** [ossfriday/ossfriday#29]
@bkeepers, @mikemcquaid and I talked this week about having people sign up for an email series, as a way to measure program adoption and success. (Mike pointed out that with ex. a calendar invite, we won't know whether people are actually participating, nor who they are.)

We were thinking of starting with 8 weekly emails that you'd receive when you sign up, containing helpful tips around contributing to open source.

I started drafting ideas for an email campaign here: https://docs.google.com/a/github.com/document/d/1KK1ylt4w_pbN72UfnbUUepBzGz46FifhVEMMY6lfkz8/edit?usp=sharing

The downside, as you can see, is someone doesn't even learn how to contribute until several weeks in. Which is probably bad.

So, we have to make some assumptions here:

* **People are experienced contributors,** so we should show them interesting tips/quotes/anecdotes to keep them motivated (ex. _"Here's how to manage your notifications"_ or _"Did you know...?"_)
* **People are experienced contributors,** but aren't contributing during work, so the content is more about how to talk about open source at work, get employers on board, etc.
* **People don't know how to contribute,** so we should show them little ways to get started and make each week more actionable

I'm leaning towards the first option. I don't think this program is about handholding 100% new contributors, that's why we have the guides. But I don't want to make assumptions.

The downside of the first option also is it's less structured, so we have to make it not feel abrupt when they end after 8 weeks.

@bkeepers @MikeMcQuaid what do you think?

**Comment by MikeMcQuaid** [comment]
> I'm leaning towards the first option. I don't think this program is about handholding 100% new contributors, that's why we have the guides. But I don't want to make assumptions.

I'm leaning towards that too. We either assume experience or the home page is the place that they get signposted to Open Source Guides that can help them get started.

An option that would be more work is asking people on signup whether they are maintainers/contributors/companies and experienced/unexperienced and tailoring at least some content accordingly.

I like the ideas and where we're at with this so far, though.

**Comment by bkeepers** [comment]
> I'm leaning towards the first option. I don't think this program is about handholding 100% new contributors, that's why we have the guides. But I don't want to make assumptions.

👍 makes sense tor me. Getting people contributing who already have the skills but just need a nudge is the highest impact/lowest effort thing we can do, and then we can work on removing other barriers.

> An option that would be more work is asking people on signup whether they are maintainers/contributors/companies and experienced/unexperienced and tailoring at least some content accordingly.

I was wondering about this too. What about a question like this:

> What are you interested in dong on Open Source Friday?
>
> - [ ] Finding a project to contribute to
> - [ ] Learning how to become a better contributor
> - [ ] Releasing and growing my own open source project
> - [ ] Helping my leadership, legal team, and coworkers understand the value of open source

Those questions probably aren't exactly right, but something like that.

**Comment by nayafia** [comment]
(EDIT: updated doc sharing permissions to public. Sorry bout that!)

Awesome, I'll start brainstorming in that realm then.

Asking a q upon signup sounds good to me. I don't think it's worth the investment to develop tailored content, when don't yet know our audience, but that way we'll at least be able to understand them moving forward. 

Perhaps:

> Why are you signing up for Open Source Friday?
> - [ ] I want to start contributing to open source.
> - [ ] I want motivation to contribute more regularly.
> - [ ] I want to get contributors for my own project.
> - [ ] I want to help my colleagues understand the value of open source.
> - [ ] Other (please explain)

**Comment by nayafia** [comment]
Although: we should get clear on our CTAs for each segment. Ideally only contributors should be signing up for the email list.

I'm gonna open a separate issue for that.

**Comment by MikeMcQuaid** [comment]
@nayafia and I talked in a video chat and we decided to not bother with emails for now.
