### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by andrew** [ossfriday/ossfriday#3]
Minimal 🚢  list:

- [x] Login with GitHub (to get weekly reminder emails and track progress)
- [x] Homepage explaining what #ossfriday is and how to get involved
- [ ] Dynamic list of issues labeled `ossfriday` from GitHub
- [x] Documentation for maintainers on how to get involved
- [ ] Links to related services and contribution guides/blogposts
- [ ] Basic diary functionality for logged in users to say what they did (markdown)
- [ ] Social sharing badges
- [ ] Meta tags for twitter/facebook shares

**Comment by benpolinsky** [comment]
Hey there - 

I'd be down to help out where I can.  
What are you thinking for Login w/ Github?  Devise/Omniauth?

**Comment by andrew** [comment]
@benpolinsky yeah omniauth login would be ideal 👍

**Comment by Charlotteis** [comment]
Second point was done by #11

**Comment by m1guelpf** [comment]
@andrew Expected launch day? The issue says 6th January...

**Comment by Thetoxicarcade** [comment]
do you mean anything in ossfriday if they subscribe to the repo, or any issue (globally) tagged ossfriday?

also, do you want static pngs, svgs, or weird svg/js hybrids for social share icons?

**Comment by MikeMcQuaid** [comment]
@m1guelpf I've edited it.

**Comment by MikeMcQuaid** [comment]
> also, do you want static pngs, svgs, or weird svg/js hybrids for social share icons?

@Thetoxicarcade Most likely: yes and probably SVGs? I'd imagine GitHub/GitLab/Bucket READMEs will be the primary place they'd be found.

**Comment by MikeMcQuaid** [comment]
Closing this in favour of https://github.com/ossfriday/ossfriday/issues/21 just because I felt weird about editing @andrew's initial checklist to be not his roadmap. Thanks to @andrew for thinking this to start with and getting me started here 🙇‍♀️ 👍 ❤️
