### ISSUE TITLE
Add other audience sections to footer of each page

### ISSUE THREAD

**Issue by nayafia** [ossfriday/ossfriday#31]
The homepage has this footer:

<img width="1088" alt="screen shot 2017-04-06 at 1 55 13 pm" src="https://cloud.githubusercontent.com/assets/1840802/24775609/77e0ce26-1ad2-11e7-89e6-410c39c2cc55.png">

After clicking to the other pages, I kind of expected to see the same footer again. But links to other pages are only in the nav.

Does it make sense to add the footer to the other two audience pages, too?

cc @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
It turns from a footer to a header. I don't have strong opinions on this but I have "gone looking" for the header on the main page before and got confused. CC @bkeepers for thoughts as this was his original thing.

**Comment by nayafia** [comment]
> I have "gone looking" for the header on the main page before and got confused

ya that's what I was doing, but for the footer. I think either/both is fine (though I prefer how prominent the footer is), but consistency would be good.

**Comment by bkeepers** [comment]
👍  on both

**Comment by MikeMcQuaid** [comment]
Doing the footer in https://github.com/ossfriday/ossfriday/issues/37. Can't find a way to put header on main page without feeling weird.
