### ISSUE TITLE
What do we want each segment to do?

### ISSUE THREAD

**Issue by nayafia** [ossfriday/ossfriday#32]
My thoughts so far:

- **Contributors:** sign up for email list
- **Maintainers:** improve their project
- **Corporate decision makers:** encourage employees to contribute

How do we track the success of the 2nd two CTAs? Do we need to?

For maintainers, I could see us making a separate email list, but I also don't want to get too bogged down in lists (especially as we don't really have capacity to maintain them).

For corporate, we could measure by number of official partnerships, or if we offer special content (ex. policy kit), number of downloads.

I'm also inclined to just focus on messaging and reaching contributors to start, as that seems to be the main point of this program.

@MikeMcQuaid @bkeepers

**Comment by MikeMcQuaid** [comment]
> How do we track the success of the 2nd two CTAs? Do we need to?

I guess we'll track contributions with the OAuth app: https://github.com/ossfriday/ossfriday/issues/34

> For corporate, we could measure by number of official partnerships, or if we offer special content (ex. policy kit), number of downloads.

This seems reasonable/sensible.

**Comment by nayafia** [comment]
Yep, I think it's:

Audience | Message | Call to Action | Metric
------------ | ------------- | ------------- | -------------
Contributors | Contribute regularly, as part of your job | OAuth signup | # of Friday contributions (tracked in app)
Maintainers | Improve your project | OAuth signup | # Friday contributions to a project they have commit access to (tracked in app?)
Companies | Encourage employees to contribute | Sign up for policy kit | Number of kit downloads

I don't *love* the corporate one (feels like there should be a smaller CTA here), but I think the most important metric overall is the contributor one, so it's ok.

@mikemcquaid Given the above, I wonder whether we can track maintainer contributions slightly differently in the app dashboard. I'll close this out and comment in the relevant issue.

**Comment by nayafia** [comment]
Scratch that, I thought about it and realized it will get complicated. There are maintainer- and contributor-specific actions, but those aren't always distinct people (ex. a maintainer who also wants to contribute regularly), and I don't want to force people into buckets.

Ignore me, we're good!

**Comment by nayafia** [comment]
Updated table above. We'll track Friday contributions in the app. If we ever needed to slice by commit access, we could prob pull that data, but we don't need to overthink it.
