### ISSUE TITLE
Move business messaging back to separate page

### ISSUE THREAD

**Issue by bkeepers** [ossfriday/ossfriday#33]
I showed the site and talked through some ideas with @amateurhuman and he had some really good feedback.

He said, as a developer, seeing "your business depends on it" as the first headline on the page isn't very inspiring. His thought was "this isn't for me".

- Move business messaging back to its own page
- Keep the homepage really simple with what this thing is and how you can get involved:
  1. contribute to a project
  2. or, improve the onboarding experience of a project you maintainer
  3. or, help your company improve their open source practices/policies/etc.

Thoughts @MikeMcQuaid @nayafia ?

**Comment by nayafia** [comment]
Yep, this is in line with my feedback from https://github.com/ossfriday/ossfriday/pull/30#issuecomment-292579574. I totally agree.

The more I think about it, the more I think we should model after 24PR as a baseline, then simply add the other parts we need (maintainer/company info pages). But primary messaging should be contributor-centric.

**Comment by MikeMcQuaid** [comment]
My concern is that the business-centric part of this is a differentiator. I'd think developers are more likely to hear about this through somewhere with a summary and click through to their relevant page (although we could put that navigation nearer the top but I'd need design help). The "businesses" segment are less likely to click around this site to find what something that grabs them. Thoughts?

**Comment by nayafia** [comment]
Again, I'd think about this from a sharing perspective:

We expect developers, not companies, to share this initiative around, so the landing page should speak to them. (i.e. if a developer doesn't want to participate, the company sure isn't going to advocate for it.)

We expect developers to send a specific link to their employers, so the company page can live on a page elsewhere.

I think it's less likely that we'll reach people by a company's, say, CTO stumbling upon the page and being psyched to make all their engineers participate in open source. It's more likely that a developer in the company will get excited and rally everyone else internally.

If my assumptions are incorrect in terms of how this will be shared, I'm totally up for rethinking it.

**Comment by MikeMcQuaid** [comment]
@nayafia You've convinced me 👍
