### ISSUE TITLE
Use OAuth app to track participation

### ISSUE THREAD

**Issue by nayafia** [ossfriday/ossfriday#34]
We've been brainstorming how to measure participation in Open Source Fridays. Right now, the plan is to have people sign up for a weekly email series.

Seeing as Open Source Fridays is meant to be 52 Pull Requests :wink: I went back to https://24pullrequests.com/ for inspiration. They ask people to "sign up with GitHub", which gives you:

* Quick form to sign up for emails
* Dashboard that tracks how many contributions you've made since signing up

I like the idea of seeing how many contributions you've made; that's a natural motivator. And OAuth app feels more intuitive than email, since it integrates with your GitHub account. It's also something we can build on as the program grows.

I know this isn't a trivial decision, so looking to @MikeMcQuaid @bkeepers for input, as well as @andrew on whether that's been useful for 24PR.

**Comment by bkeepers** [comment]
👍  I assumed we would do the GitHub OAuth as the way of signing up

> Dashboard that tracks how many contributions you've made since signing up

This part makes me a little nervous since it could easily turn into a huge feature. We should probably flesh this out a little more to get an idea of what it would show.

**Comment by nayafia** [comment]
We discussed this F2F, we're gonna try showing number of contributions made every Friday since signing up for the program. ```mikemcquaid``` added it to his todos.
