### ISSUE TITLE
Feedback on copy from @stephbwills/@yourfrienderin

### ISSUE THREAD

**Issue by nayafia** [ossfriday/ossfriday#35]
Hey y'all, apologies for weird format but figured this was the best way to do it.

@stephbwills @yourfrienderin We did a first pass at copy on https://open-source-friday.githubapp.com/. Can you review? 

Comments on here are fine, or you can start a PR.

NOTE:

* CTAs will change (we'll ask ppl to sign up for emails or connect GitHub acct)
* Images of the Guides are mostly placeholders for now
* We're gonna make the homepage point to contributors, not companies (https://github.com/ossfriday/ossfriday/issues/33), so think of the pages as standalone

(For others following along: meet @stephbwills, who does brand editorial, and @yourfrienderin, who does business marketing, at GitHub! I've asked them to provide feedback as they're both editorial super-:star:s.)

**Comment by nayafia** [comment]
A few qs for @yourfrienderin (as I think the company page needs the most :heart:):

- [ ] How do you feel about the corporate benefits we've listed? Are any of them more or less useful?
- [ ] What should the CTA be for companies? Ideally, their job is to encourage/not actively block employees from participating in OSS Fridays.

**Comment by stephbwills** [comment]
Hi! I added some suggestions in this google doc: https://docs.google.com/a/github.com/document/d/14zPDhTTm27HA7vbeNzB4FuCCchckIRiCZXA8r3oAqaM/edit?usp=sharing

Not ideal, but I hope it's an OK way to give you feedback?

**Comment by nayafia** [comment]
@stephbwills thank you! GDoc is fine. Could you also take a look at the other two pages?

* https://open-source-friday.githubapp.com/contributors
* https://open-source-friday.githubapp.com/maintainers

(They're both equally light on copy, so hopefully it's not too much to ask :innocent:)

**Comment by stephbwills** [comment]
More edits right here! https://docs.google.com/a/github.com/document/d/1OtFqlBIimtRv63XxZ0_HhZD6s9doc8Vt_0I1au6UH4U/edit?usp=sharing

For some reason, suggestions only worked for, like, half of the doc. I highlighted my changes in green. I think the Maintainer copy needed the most work. There was a lot of repetition in the language. I didn't make a note of it, but that's what most of my changes were attempting to fix. If you don't feel like accepting a change, that's fine! Just watch out to make sure you're not using "time" or "project" too frequently!

**Comment by nayafia** [comment]
@stephbwills thank you so much, this is super helpful! I'll start a PR for changes.

**Comment by yourfrienderin** [comment]
I made comments directly in @stephbwills 's doc. Hopping on a ✈️  but hopefully all makes sense?

**Comment by nayafia** [comment]
Closed, tracking here: https://github.com/ossfriday/ossfriday/pull/41
