### ISSUE TITLE
Using an "ossfridays" label

### ISSUE THREAD

**Issue by nayafia** [ossfriday/ossfriday#43]
Re-reading @andrew's issue (#2), he suggests:

> Focusing on issues rather than projects - trying to find a project to contribute to and then find something to do on that project is tricky, instead let's get maintainers to label issues that they want to promote to new contributors with ``ossfriday`` along with related labels like ``Your First PR``, ``first-timers-only`` and ``help wanted``

@mikemcquaid any reason we would not want to encourage maintainers to do this? It could be another CTA on the maintainer page.

Pros:
* Helps us track participation
* Helps maintainers flag appropriate issues
* Helps contributors find ways to help

Cons:
* Yet Another Label (as Andrew points out, there are a bunch of others already)
* We've already got a system for tracking participation (OAuth)

I know this got overwhelming for maintainers with Hacktoberfest, but since there's less gamification ("open 4 PRs and get a T-shirt") I don't think there'd be spammy incentives?

**Comment by MikeMcQuaid** [comment]
Yeh, I'd personally really rather avoid another label. I think pointing to existing tools to find welcoming projects, making the motivation a bit more intrinsic and not gamifying should help keep the spam lower.

**Comment by nayafia** [comment]
:cool:!
