### ISSUE TITLE
Missing - Getting Setup

### ISSUE THREAD

**Issue by maxcell** [ossfriday/ossfriday#5]
Howdy! I really love this initiative and wanted to see if I could help out in any way! I was taking a look through your [CONTRIBUTING.md section on setup](https://github.com/ossfriday/ossfriday/blob/master/CONTRIBUTING.md#setup-instructions) and noticed you link to ["Getting Started"](https://github.com/ossfriday/ossfriday/blob/master/Readme.md#getting-started) on the README.md but it is a dead link because there is no section.

If you don't mind, I would love to help out! I have a general idea of how to do it just given that I had to figure it out myself just a bit ago.

0. (This might not be something everyone knows but could be helpful) Be sure to have a Ruby Version Manager even if it isn't RVM. 
1. Get the working version of Ruby installed (`2.4.0`) (I believe) 
  a. Switch over to the version of ruby
2. Install the necessary gems: `bundle install`
3. Make sure to have your `ossfriday` Postgres database
4. Migrations: `rails db:migrate`
5. Spin up the server: `rails s` or `rails server`

I know in the file, it talks about in-depth and I would love any feedback about what we should/shouldn't include. However, I think it would be great to involve this now versus taking it on later and forgetting and excluding assistance from the community :smile:

**Comment by andrew** [comment]
Nice thinking @maxcell, I'd be inclined to use the same section from 24pullrequests: https://github.com/24pullrequests/24pullrequests#getting-started as I'm planning on borrowing a lot of code from there!

**Comment by maxcell** [comment]
And I think that's more than fine! I just wanted to be sure to get it written down. If you want me to go ahead and try to put that together for what is there, I don't mind!
