### ISSUE TITLE
Site not found

### ISSUE THREAD

**Issue by JoseCage** [ossfriday/ossfriday#6]
Hello..

I have tried to visit the [**OssFriday Website**](http://ossfriday.com/) and return 404 error from GitHub Pages.. 

I would like somehow to see the project and participate.

Are there any predictions of when the site might be online?

![404](https://cloud.githubusercontent.com/assets/4200487/21981758/47652774-dbe9-11e6-83b8-b144fa027740.PNG)

**Comment by Charlotteis** [comment]
@JoseCage the website hasn't been built yet.

I know @andrew has plans to get to it in the next few weeks.

**Comment by JoseCage** [comment]
Thanks @Charlotteis..

I'm Tuned.. 👀
