### ISSUE TITLE
Confused by lack of "contributor" navigation

### ISSUE THREAD

**Issue by kytrinyx** [ossfriday/ossfriday#63]
When I was on the user page, I saw the business and maintainer navigation and wondered where to go to find the contributor page. 

<img width="839" alt="screen shot 2017-06-06 at 5 14 24 pm" src="https://user-images.githubusercontent.com/276834/26861200-8f5d8988-4aff-11e7-8fe2-a93da2b77e5f.png">

It wasn't until later that I realized that the contributor page is on the homepage.

I don't know whether this is a real problem, or just me being confused or dense, but I thought I'd mention it in case anyone has thoughts about mitigating potential confusion.

**Comment by MikeMcQuaid** [comment]
@kytrinyx I guess my thinking was that the "contributor page" is also technically the homepage and general practise seems to be to have the title link back to the homepage. Thoughts?

**Comment by kytrinyx** [comment]
@MikeMcQuaid Yeah, I got that... eventually :) The thing is, we know that, but people browsing the site don't necessarily.

How about removing the top level nav completely, and only having the homepage plus the two links at the bottom of each page to take you to wherever you are not?

**Comment by MikeMcQuaid** [comment]
I (unsurprisingly) kinda like it as-is 😅. Let's get @nayafia in here at some point to help tie-break.

**Comment by kytrinyx** [comment]
Works for me :-)

**Comment by nayafia** [comment]
Sorry I missed this! I'm with @kytrinyx, I think removing the top level nav makes sense. It'd be nice to have both, but I see why it's confusing.

**Comment by nayafia** [comment]
Or: add "contributors" to top nav (but then that could be confusing with the homepage).

**Comment by MikeMcQuaid** [comment]
This will be addressed by https://github.com/ossfriday/ossfriday/issues/73
