### ISSUE TITLE
Getting 404 when clicking on link in repo description

### ISSUE THREAD

**Issue by GiacomoLaw** [ossfriday/ossfriday#7]
Getting a 404 telling me that there is no Github pages site when clicking in the description header.

**Comment by JoseCage** [comment]
Take look at #6 

![404](https://cloud.githubusercontent.com/assets/4200487/22346176/666b1e22-e403-11e6-919e-579bb60a9e38.png)

**Comment by GiacomoLaw** [comment]
Okay, thanks.

**Comment by JoseCage** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9945775-227153730_1-s4-v1.png?transparent=1&palette=1&width=246)
