### ISSUE TITLE
Update Primer Version

### ISSUE THREAD

**Issue by sophshep** [ossfriday/ossfriday#92]
This will allow us to do a few things: 

* Use newly refactored container styles (so there are less flexbox bugs)
* Use new gutter styles

**Comment by MikeMcQuaid** [comment]
@sophshep Any thoughts on this one?

**Comment by sophshep** [comment]
I'll add it to my list of things to do once the craziness of Universe is over 😄 

Sorry I haven't gotten to it yet!

**Comment by MikeMcQuaid** [comment]
@sophshep Thanks and no worries, just wanted to check ❤️
